version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: elasticsearch
    ports:
      - "7200:9200"
      - "7300:9300"
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.1
    container_name: kibana
    volumes:
      - ./kibana.yml:/Users/oleciwoj/Projects/elasticsearch/docker/kibana/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk
networks:
  elk:
    driver: bridge
